ci fixes

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -114,132 +114,134 @@ jobs:
         env:
           CARGO_TERM_COLOR: always
         run: |
-          cargo install cargo-edit
-          cargo metadata --format-version=1 --no-deps --manifest-path=../librustzcash/Cargo.toml | jq -r '.packages[] | .name' | xargs -I {} sh -c "cargo upgrade -p {} --manifest-path=../librustzcash/Cargo.toml -i"
-          cargo build --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml &> build_output
-          if [[ "$?" != "0" ]]; then
-            echo "BUILD_FAILING=true" >> $GITHUB_ENV
-          else
-            echo "BUILD_FAILING=false" >> $GITHUB_ENV
-          fi
-
-      # Run only if an issue doesnt exist and the build fails
-      - name: Diff public API changes between outdated libs
-        if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
-        env:
-          CARGO_TERM_COLOR: always
-        run: |
-          IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
-
-          # use the cargo-public-api tool to diff the public APIs of different versions
-          cargo +stable -q install cargo-public-api --locked
-
-          for lib_name in "${arr[@]}"; do
-            if [ -z "$lib_name" ]; then
-              continue
-            fi
-
-            # this is faster than "cargo outdated", especially in a loop
-            LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
-            LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')
-
-            git -C ./librustzcash fetch -q --tags
-            # This counts on the fact that they always name their releases in format lib_name-semver (ex zcash_address-0.1.0)
-            git -C ./librustzcash checkout -q tags/$lib_name-$LIB_LATEST_VERSION
-
-            # write the diff to files, which we show in the next step for better readability
-            cargo public-api --color=always --manifest-path=./librustzcash/Cargo.toml -p "$lib_name" -sss diff "$LIB_CURRENT_VERSION" > "${lib_name}.diff"
-          done
-
-      # Step only for better diff visibility and linkability
-      # If you change the name of this step, make sure it's changed in the "Create workflow summary" gh command too
-      - name: Show public API diffs
-        if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
-        run: |
-          IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
-
-          for lib_name in "${arr[@]}"; do
-            if [ -z "$lib_name" ]; then
-              continue
-            fi
-            echo "---"
-            echo "${lib_name}"
-            echo "---"
-            cat "${lib_name}.diff"
-            echo ""
-          done
-
-      - name: Create workflow summary
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          if [[ "$LIBS_UP_TO_DATE" == "true" ]]; then
-            echo "# :white_check_mark: All libraries from librustzcash are up to date :white_check_mark: " >> $GITHUB_STEP_SUMMARY
-            exit 0
-          fi
-
-          if [[ "$ISSUE_ALREADY_EXISTS" == "true" ]]; then
-            echo "# :page_with_curl: An issue already exists for those library versions :page_with_curl: " >> $GITHUB_STEP_SUMMARY
-            echo "**[VIEW EXISTING ISSUE]($EXISTING_ISSUE_URL)**" >> $GITHUB_STEP_SUMMARY
-            exit 0
-          fi
-
-          IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
-
-          echo "# :warning: New versions of librustzcash libraries are present :warning: " >> $GITHUB_STEP_SUMMARY
-
-          for lib_name in "${arr[@]}"; do
-            if [ -z "$lib_name" ]; then
-              continue
-            fi
-
-            LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
-            LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')
-
-            echo "## ${lib_name}" >> $GITHUB_STEP_SUMMARY
-            echo "\`CURRENTLY USED VERSION\`    :arrow_right: ${LIB_CURRENT_VERSION}" >> $GITHUB_STEP_SUMMARY
-            echo "\`LATEST PUBLISHED VERSION\`  :arrow_right: ${LIB_LATEST_VERSION}" >> $GITHUB_STEP_SUMMARY
-            echo ""
-            echo "\`\`\`diff"
-            echo $(cat $lib_name.diff)
-            echo "\`\`\`"
-          done
-
-          workflow_url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "${{ github.job }}") | .url, (.steps[] | select(.name == "Show public API diffs") | "#step:\(.number):1")' | tr -d "\n")
-          echo "**[VIEW PUBLIC API DIFF]($workflow_url)**" >> $GITHUB_STEP_SUMMARY
-
-          echo "BUILD_FAILING"
-          echo $BUILD_FAILING
-          cat build_output
-          if [[ "$BUILD_FAILING" == "true" ]]; then
-            echo "# :warning: Build fails after bumping to the newer versions with the following output: :warning: " >> $GITHUB_STEP_SUMMARY
-          fi
-
-          if [[ "$BUILD_FAILING" == "false" ]]; then
-            echo "# :white_check_mark: Build doesn't fail when bumping to the newer versions :white_check_mark: " >> $GITHUB_STEP_SUMMARY
-          fi
-
-          echo "BUILD FAILING"
-          echo $BUILD_FAILING
-
-      # Run only if an issue doesnt exist and the build fails
-      - name: Create issue
-        if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          # TODO: github.job is not the id, but the name of the job
-          # Need to check if it's possible to put the job ID, in order to generate the correct anchor
-          workflow_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\#summary-${{ github.job }}
-          IFS=';' read -ra arr <<< "$ISSUE_LABELS"
-          cmd_args=("gh" "issue" "create" "--repo" "ctoyan/uniffi-zcash-lib" "--title" "New versions of librustzcash. Please review." "--body" "[Check workflow summary]($workflow_url)")
-          # Loop through each library(out of $USED_LIBS) and add it as a -p argument value
-          for lib_name in "${arr[@]}"; do
-            cmd_args+=("--label" "$lib_name")
-          done
-
-          for cmd_arg in "${cmd_args[@]}"; do
-            echo $cmd_arg
-          done
-
-          "${cmd_args[@]}"
+          pwd
+          ls -la
+      #     cargo install cargo-edit
+      #     cargo metadata --format-version=1 --no-deps --manifest-path=../librustzcash/Cargo.toml | jq -r '.packages[] | .name' | xargs -I {} sh -c "cargo upgrade -p {} --manifest-path=../librustzcash/Cargo.toml -i"
+      #     cargo build --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml &> build_output
+      #     if [[ "$?" != "0" ]]; then
+      #       echo "BUILD_FAILING=true" >> $GITHUB_ENV
+      #     else
+      #       echo "BUILD_FAILING=false" >> $GITHUB_ENV
+      #     fi
+      #
+      # # Run only if an issue doesnt exist and the build fails
+      # - name: Diff public API changes between outdated libs
+      #   if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
+      #   env:
+      #     CARGO_TERM_COLOR: always
+      #   run: |
+      #     IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
+      #
+      #     # use the cargo-public-api tool to diff the public APIs of different versions
+      #     cargo +stable -q install cargo-public-api --locked
+      #
+      #     for lib_name in "${arr[@]}"; do
+      #       if [ -z "$lib_name" ]; then
+      #         continue
+      #       fi
+      #
+      #       # this is faster than "cargo outdated", especially in a loop
+      #       LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
+      #       LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')
+      #
+      #       git -C ./librustzcash fetch -q --tags
+      #       # This counts on the fact that they always name their releases in format lib_name-semver (ex zcash_address-0.1.0)
+      #       git -C ./librustzcash checkout -q tags/$lib_name-$LIB_LATEST_VERSION
+      #
+      #       # write the diff to files, which we show in the next step for better readability
+      #       cargo public-api --color=always --manifest-path=./librustzcash/Cargo.toml -p "$lib_name" -sss diff "$LIB_CURRENT_VERSION" > "${lib_name}.diff"
+      #     done
+      #
+      # # Step only for better diff visibility and linkability
+      # # If you change the name of this step, make sure it's changed in the "Create workflow summary" gh command too
+      # - name: Show public API diffs
+      #   if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
+      #   run: |
+      #     IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
+      #
+      #     for lib_name in "${arr[@]}"; do
+      #       if [ -z "$lib_name" ]; then
+      #         continue
+      #       fi
+      #       echo "---"
+      #       echo "${lib_name}"
+      #       echo "---"
+      #       cat "${lib_name}.diff"
+      #       echo ""
+      #     done
+      #
+      # - name: Create workflow summary
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   run: |
+      #     if [[ "$LIBS_UP_TO_DATE" == "true" ]]; then
+      #       echo "# :white_check_mark: All libraries from librustzcash are up to date :white_check_mark: " >> $GITHUB_STEP_SUMMARY
+      #       exit 0
+      #     fi
+      #
+      #     if [[ "$ISSUE_ALREADY_EXISTS" == "true" ]]; then
+      #       echo "# :page_with_curl: An issue already exists for those library versions :page_with_curl: " >> $GITHUB_STEP_SUMMARY
+      #       echo "**[VIEW EXISTING ISSUE]($EXISTING_ISSUE_URL)**" >> $GITHUB_STEP_SUMMARY
+      #       exit 0
+      #     fi
+      #
+      #     IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
+      #
+      #     echo "# :warning: New versions of librustzcash libraries are present :warning: " >> $GITHUB_STEP_SUMMARY
+      #
+      #     for lib_name in "${arr[@]}"; do
+      #       if [ -z "$lib_name" ]; then
+      #         continue
+      #       fi
+      #
+      #       LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
+      #       LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')
+      #
+      #       echo "## ${lib_name}" >> $GITHUB_STEP_SUMMARY
+      #       echo "\`CURRENTLY USED VERSION\`    :arrow_right: ${LIB_CURRENT_VERSION}" >> $GITHUB_STEP_SUMMARY
+      #       echo "\`LATEST PUBLISHED VERSION\`  :arrow_right: ${LIB_LATEST_VERSION}" >> $GITHUB_STEP_SUMMARY
+      #       echo ""
+      #       echo "\`\`\`diff"
+      #       echo $(cat $lib_name.diff)
+      #       echo "\`\`\`"
+      #     done
+      #
+      #     workflow_url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "${{ github.job }}") | .url, (.steps[] | select(.name == "Show public API diffs") | "#step:\(.number):1")' | tr -d "\n")
+      #     echo "**[VIEW PUBLIC API DIFF]($workflow_url)**" >> $GITHUB_STEP_SUMMARY
+      #
+      #     echo "BUILD_FAILING"
+      #     echo $BUILD_FAILING
+      #     cat build_output
+      #     if [[ "$BUILD_FAILING" == "true" ]]; then
+      #       echo "# :warning: Build fails after bumping to the newer versions with the following output: :warning: " >> $GITHUB_STEP_SUMMARY
+      #     fi
+      #
+      #     if [[ "$BUILD_FAILING" == "false" ]]; then
+      #       echo "# :white_check_mark: Build doesn't fail when bumping to the newer versions :white_check_mark: " >> $GITHUB_STEP_SUMMARY
+      #     fi
+      #
+      #     echo "BUILD FAILING"
+      #     echo $BUILD_FAILING
+      #
+      # # Run only if an issue doesnt exist and the build fails
+      # - name: Create issue
+      #   if: env.ISSUE_ALREADY_EXISTS == 'false' && env.BUILD_FAILING == 'true'
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   run: |
+      #     # TODO: github.job is not the id, but the name of the job
+      #     # Need to check if it's possible to put the job ID, in order to generate the correct anchor
+      #     workflow_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\#summary-${{ github.job }}
+      #     IFS=';' read -ra arr <<< "$ISSUE_LABELS"
+      #     cmd_args=("gh" "issue" "create" "--repo" "ctoyan/uniffi-zcash-lib" "--title" "New versions of librustzcash. Please review." "--body" "[Check workflow summary]($workflow_url)")
+      #     # Loop through each library(out of $USED_LIBS) and add it as a -p argument value
+      #     for lib_name in "${arr[@]}"; do
+      #       cmd_args+=("--label" "$lib_name")
+      #     done
+      #
+      #     for cmd_arg in "${cmd_args[@]}"; do
+      #       echo $cmd_arg
+      #     done
+      #
+      #     "${cmd_args[@]}"
